### ISSUE TITLE
Maintenance features - Database health - Row sizes as per Kentico recommendations.

### ISSUE THREAD

**Issue by martbrow** [Kentico/KInspector#61]
Hi,

https://devnet.kentico.com/articles/maintenance-in-kentico?feed=Kentico

There are some elements of this article that aren't represented in KInspector, I'm not sure if you would prefer an idea per request?

It looks like a number of them are easy to implement - I'd be happy to look at them if you agree:

"Database Health"

1) Event Logs - Kentico recommend that the Event Log is set to 5,000-10,000 entries - it would be easy to query the table to check the size and return a warning if it's outside this range (and maybe critical for extreme settings?)

2) Web Farm Tasks - We've seen the table get quite large when a server is out of the web farm, I'm not sure of what would be considered 'too large' but if this table has a high number of rows (to be defined by Kentico) it most likely indicates that there is a problem.

**Comment by petrsvihlik** [comment]
1) I totally agree with this one.
2) This issue has been solved in Kentico 9, I believe. Check out the ['Not responding'](https://docs.kentico.com/display/K9/Troubleshooting+web+farms) status in the documentation. So I don't think it has high priority.

**Comment by ondrejsevcik** [comment]
2) maybe we can create a module for versions before v9, where the issue is still present.

**Comment by martbrow** [comment]
For 2) I assume if the version is excluded for 9.0 for the module then it's useful for 8.x users as the product is still officially supported by Kentico.  Do you have an option on what would be 'too many rows' for the tasks in the table?

**Comment by martbrow** [comment]
Before I create a pull request :-)

Would it make sense to create a single module for general row size checks - like OMTablesSize.cs but for more general CMS tables.  If these were created as individual modules then as additional best practice table sizes become apparent they can be added to this module rather than spawning lots of new modules?

It could be added as \Modules\General\CMSTablesSize.cs?

**Comment by petrsvihlik** [comment]
2) I would base the check on tasks' age rather than on their amount. So, if there is a task older than 24 hours the app should report an error. This way it would be in line with the [24 hour threshold in Kentico 9](https://docs.kentico.com/display/K9/Troubleshooting+web+farms). 
After 24 hours we can quite safely assume that it's not a server maintenance what's causing problems.

In general, I agree with having CMSTablesSize but we'll do without it this time. We should put the implementation in a separate module. 
What do you say?

**Comment by ondrejsevcik** [comment]
Just a note: We already have a module displaying ['Top 25 tables by size'](https://github.com/Kentico/KInspector/blob/master/KInspector.Modules/Modules/General/BigTablesModule.cs).
